# Generated by Django 4.1 on 2023-08-30 11:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                ("documentid", models.AutoField(primary_key=True, serialize=False)),
                ("documenttitle", models.CharField(max_length=255)),
                ("documentcontent", models.TextField()),
            ],
            options={
                "db_table": "Document",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("projectid", models.AutoField(primary_key=True, serialize=False)),
                ("projectname", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "Project",
            },
        ),
        migrations.CreateModel(
            name="PublicChat",
            fields=[
                ("chatid", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "PublicChat",
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                ("teamid", models.AutoField(primary_key=True, serialize=False)),
                ("teamname", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "Team",
            },
        ),
        migrations.CreateModel(
            name="TeamToProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("teamid", models.IntegerField(default=0, verbose_name="团队")),
                ("projectid", models.IntegerField(default=0, verbose_name="项目")),
            ],
        ),
        migrations.CreateModel(
            name="TeamToUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("teamid", models.IntegerField(default=0, verbose_name="主体")),
                ("userid", models.IntegerField(default=0, verbose_name="成员")),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("userid", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("nickname", models.CharField(max_length=128)),
                ("password", models.CharField(max_length=255)),
                ("sex", models.CharField(default="", max_length=12, verbose_name="性别")),
                (
                    "birthday",
                    models.CharField(default="", max_length=32, verbose_name="生日"),
                ),
                (
                    "location",
                    models.CharField(default="中国大陆", max_length=32, verbose_name="所在地"),
                ),
                (
                    "avatar_url",
                    models.CharField(default="", max_length=128, verbose_name="用户头像路径"),
                ),
                ("avatar", models.FileField(upload_to="", verbose_name="用户头像")),
                (
                    "last_login",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="最后登录时间"
                    ),
                ),
            ],
            options={
                "db_table": "User",
            },
        ),
        migrations.CreateModel(
            name="UserToTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userid", models.IntegerField(default=0, verbose_name="主体")),
                ("teamid", models.IntegerField(default=0, verbose_name="团队")),
            ],
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                ("teammemberid", models.AutoField(primary_key=True, serialize=False)),
                ("role", models.CharField(max_length=255)),
                (
                    "teamid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.team"
                    ),
                ),
                (
                    "userid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.user"
                    ),
                ),
            ],
            options={
                "db_table": "TeamMember",
            },
        ),
        migrations.AddField(
            model_name="team",
            name="creatorid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user.user"
            ),
        ),
        migrations.CreateModel(
            name="PublicChatMember",
            fields=[
                ("chat_member_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "chatid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.publicchat",
                    ),
                ),
                (
                    "userid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.user"
                    ),
                ),
            ],
            options={
                "db_table": "PublicChatMember",
            },
        ),
        migrations.AddField(
            model_name="publicchat",
            name="teamid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user.team"
            ),
        ),
        migrations.CreateModel(
            name="PrototypePage",
            fields=[
                ("pageid", models.AutoField(primary_key=True, serialize=False)),
                ("pagename", models.CharField(max_length=255)),
                ("pagesize", models.IntegerField()),
                ("pagecontent", models.TextField()),
                (
                    "projectid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.project"
                    ),
                ),
            ],
            options={
                "db_table": "PrototypePage",
            },
        ),
        migrations.AddField(
            model_name="project",
            name="creatorid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user.user"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="teamid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user.team"
            ),
        ),
        migrations.CreateModel(
            name="DocumentVersion",
            fields=[
                ("versionid", models.AutoField(primary_key=True, serialize=False)),
                ("versioncontent", models.TextField()),
                ("timestamp", models.DateTimeField()),
                (
                    "documentid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.document"
                    ),
                ),
            ],
            options={
                "db_table": "DocumentVersion",
            },
        ),
        migrations.AddField(
            model_name="document",
            name="projectid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user.project"
            ),
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                ("messageid", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("unread", "未读"), ("read", "已读")],
                        default="unread",
                        max_length=10,
                    ),
                ),
                (
                    "mentioneduserid",
                    models.ForeignKey(
                        default=0,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentioned_messages",
                        to="user.user",
                    ),
                ),
                (
                    "senderid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to="user.user",
                    ),
                ),
                (
                    "teamid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.team"
                    ),
                ),
            ],
            options={
                "db_table": "ChatMessage",
                "ordering": ["-timestamp"],
            },
        ),
    ]
