# Generated by Django 3.2.20 on 2023-09-03 00:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='rank',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='project',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创造时间'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('folderid', models.AutoField(primary_key=True, serialize=False)),
                ('foldertitle', models.CharField(max_length=255)),
                ('documentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.document')),
                ('projectid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.project')),
            ],
            options={
                'db_table': 'Folder',
            },
        ),
    ]
