# Generated by Django 3.2.20 on 2023-09-03 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20230903_0040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='rank',
        ),
    ]
